spring:
  application:
    name: git-test
  redis:
    database: 0
    host: 192.168.37.25
    port: 6379
    password:
    timeout: 20000
    pool:
      max-active: 600
      max-wait: -1
      max-idle: 200
      min-idle: 1
  data:
    mongodb:
      database: gis
      host: 192.168.37.25
      port: 27017
      password: